// Generates assets/data/countries.js and assets/data/regions.js from
// country-config.mjs (the roster) + Natural Earth (names, ISO-2, capitals).
//
//   node build-data.mjs
//
// Natural Earth carries NAME_FR / NAME_EN on both countries and populated
// places, so French names come from the data rather than by hand; OVERRIDES in
// country-config.mjs fixes the entries where NE is stale or long-winded.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CONTINENTS, WORLD, REGION_MEMBERS, OVERRIDES, MICRO_KM2, AREA_KM2, AFRICA_EXEMPT, MAX_NAME_LEN, MAJOR } from './country-config.mjs';
import { loadNaturalEarth } from './ne-source.mjs';
import { AFRICA_FACTS } from './facts-africa.mjs';
import { WORLD_FACTS } from './facts-world.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '..', 'assets', 'data');

const { countries: neCountries, capitals: neCapitals } = await loadNaturalEarth();

// region id -> continent id
const regionContinent = {};
for (const c of CONTINENTS) for (const r of c.regions) regionContinent[r.id] = c.id;

const problems = [];
const out = {};

for (const [regionId, ids] of Object.entries(REGION_MEMBERS)) {
  const cont = regionContinent[regionId];
  if (!cont) { problems.push(`region ${regionId} belongs to no continent`); continue; }

  for (const iso3 of ids) {
    const ne = neCountries[iso3];
    const ov = OVERRIDES[iso3] || {};
    if (!ne) { problems.push(`${iso3}: absent from Natural Earth`); continue; }

    const cap = neCapitals[iso3];
    const capFr = ov.capFr || (cap && cap.fr);
    const capEn = ov.capEn || (cap && cap.en);
    if (!capFr || !capEn) { problems.push(`${iso3}: no capital name`); continue; }

    const i2 = (ne.iso2 && ne.iso2 !== '-99') ? ne.iso2.toLowerCase() : null;
    if (!i2) { problems.push(`${iso3}: no ISO 3166-1 alpha-2 code (needed for the flag)`); continue; }

    const area = AREA_KM2[iso3];
    const micro = area !== undefined && area < MICRO_KM2;
    const exempt = AFRICA_EXEMPT.includes(iso3);

    const cf = ov.cf || ne.fr;
    const ce = ov.ce || ne.en;
    for (const [label, value] of [['cf', cf], ['ce', ce], ['capFr', capFr], ['capEn', capEn]]) {
      if (value.length > MAX_NAME_LEN) {
        problems.push(`${iso3}: ${label} "${value}" is ${value.length} chars, over the ${MAX_NAME_LEN} that fits a tray chip — add a shorter form to OVERRIDES`);
      }
    }

    out[iso3] = { i2, cont, reg: regionId, tier: (micro && !exempt) ? 2 : 1, cf, ce, capFr, capEn };
  }
}

if (problems.length) {
  console.error('build-data failed:\n  ' + problems.join('\n  '));
  process.exit(1);
}

// ---------------------------------------------------------------- countries.js
const order = Object.keys(out).sort();
const lines = order.map((id) => {
  const c = out[id];
  return `  ${id}:{i2:${J(c.i2)},cont:${J(c.cont)},reg:${J(c.reg)},tier:${c.tier},` +
         `cf:${J(c.cf)},ce:${J(c.ce)},capFr:${J(c.capFr)},capEn:${J(c.capEn)}},`;
});

const tier1 = order.filter((id) => out[id].tier === 1).length;
write('countries.js',
`// GENERATED by tools/build-data.mjs — do not edit by hand.
// Roster and corrections live in tools/country-config.mjs; re-run \`npm run data\`.
//
//   i2    ISO 3166-1 alpha-2, lowercased — the flagcdn.com file name
//   cont  continent id (see regions.js)
//   reg   region id, i.e. which card on the continent screen
//   tier  1 = in the default rounds, 2 = micro-state, in the data but not dealt
//
// ${order.length} countries, ${tier1} of them tier 1.
window.WORLD_DATA = window.WORLD_DATA || {};
window.WORLD_DATA.countries = {
${lines.join('\n')}
};
`);

// ------------------------------------------------------------------ regions.js
const contBlocks = CONTINENTS.map((c) => {
  const regions = c.regions.map((r) =>
    `    {id:${J(r.id)},fr:${J(r.fr)},en:${J(r.en)},bg:${J(r.bg)},shadow:${J(r.shadow)}},`).join('\n');
  return `  ${J(c.id)}:{fr:${J(c.fr)},en:${J(c.en)},geo:${J(c.geo)},bg:${J(c.bg)},shadow:${J(c.shadow)},emoji:${J(c.emoji)},regions:[\n${regions}\n  ]},`;
}).join('\n');

// On the world map the "regions" are the continents themselves, so the region
// card grid is reused verbatim for the ultimate challenge.
const worldRegions = CONTINENTS.map((c) =>
  `    {id:${J(c.id)},fr:${J(c.fr)},en:${J(c.en)},bg:${J(c.bg)},shadow:${J(c.shadow)}},`).join('\n');

write('regions.js',
`// GENERATED by tools/build-data.mjs — do not edit by hand.
// Region membership is not listed here: a country's \`reg\` field in
// countries.js is the single source of truth, so the two can never disagree.
window.WORLD_DATA = window.WORLD_DATA || {};
window.WORLD_DATA.continents = {
${contBlocks}
  ${J(WORLD.id)}:{fr:${J(WORLD.fr)},en:${J(WORLD.en)},geo:${J(WORLD.geo)},bg:${J(WORLD.bg)},shadow:${J(WORLD.shadow)},emoji:${J(WORLD.emoji)},world:1,regions:[
${worldRegions}
  ]},
};
window.WORLD_DATA.continentOrder = ${JSON.stringify(CONTINENTS.map((c) => c.id))};
window.WORLD_DATA.worldId = ${J(WORLD.id)};
`);

// -------------------------------------------------------------------- facts.js
const facts = { ...AFRICA_FACTS, ...WORLD_FACTS };
const factProblems = [];
for (const id of order) {
  const f = facts[id];
  if (!f) { factProblems.push(`${id}: no anecdote`); continue; }
  if (!f.fr.length || !f.en.length) factProblems.push(`${id}: an empty anecdote list`);
  if (f.fr.length !== f.en.length) {
    factProblems.push(`${id}: ${f.fr.length} French anecdotes but ${f.en.length} English — the popup picks one index for both languages, so they must match`);
  }
  if (MAJOR.includes(id) && f.fr.length < 2) factProblems.push(`${id}: listed in MAJOR but has only one anecdote`);
}
for (const id of Object.keys(facts)) if (!out[id]) factProblems.push(`${id}: anecdote for a country not in the roster`);
if (factProblems.length) {
  console.error('build-data failed:\n  ' + factProblems.join('\n  '));
  process.exit(1);
}

const factLines = order.map((id) =>
  `  ${id}:{fr:${JSON.stringify(facts[id].fr)},en:${JSON.stringify(facts[id].en)}},`);
const totalFacts = order.reduce((n, id) => n + facts[id].fr.length, 0);

write('facts.js',
`// GENERATED by tools/build-data.mjs — do not edit by hand.
// Written in tools/facts-world.mjs; the African entries come from
// africa-capitals-game via tools/extract-africa-facts.mjs.
//
// fr[i] and en[i] are the same anecdote: the popup draws one index and keeps it
// when the player switches language mid-read.
//
// ${order.length} countries, ${totalFacts} anecdotes in each language.
window.WORLD_DATA = window.WORLD_DATA || {};
window.WORLD_DATA.facts = {
${factLines.join('\n')}
};
`);

const byCont = {};
for (const id of order) byCont[out[id].cont] = (byCont[out[id].cont] || 0) + 1;
console.log(`facts.js      ${totalFacts} anecdotes per language`);
console.log(`countries.js  ${order.length} countries (${tier1} tier 1, ${order.length - tier1} micro)`);
for (const c of CONTINENTS) console.log(`  ${c.id.padEnd(15)} ${byCont[c.id] || 0}`);

function J(s) { return JSON.stringify(s); }

function write(name, body) {
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, name), body);
}
