// Anecdotes for every country outside Africa, French and English.
//
// House style, inherited from africa-capitals-game: one short sentence a child
// can picture, no dates unless the date *is* the story, nothing that reads like
// a textbook. The two arrays must stay the same length and the same order —
// switching language mid-popup keeps the fact you were reading.
//
// Countries listed in MAJOR (country-config.mjs) carry 2-3 facts so replaying a
// continent does not repeat itself; the rest carry one.

export const WORLD_FACTS = {

  // ============================================================ EUROPE

  FRA: { fr: ["Le pays le plus visité du monde.", "La tour Eiffel devait être démontée au bout de vingt ans.", "On y compte plus de mille sortes de fromages."],
         en: ["The most visited country in the world.", "The Eiffel Tower was meant to be taken down after twenty years.", "It has over a thousand kinds of cheese."] },
  DEU: { fr: ["On y a inventé l'imprimerie à caractères mobiles.", "Certaines portions d'autoroute n'ont aucune limite de vitesse.", "Berlin compte plus de ponts que Venise."],
         en: ["Movable-type printing was invented here.", "Some stretches of motorway have no speed limit at all.", "Berlin has more bridges than Venice."] },
  BEL: { fr: ["Le pays des gaufres, des frites et de la bande dessinée.", "Bruxelles abrite le siège de l'Union européenne."],
         en: ["The land of waffles, fries and comic books.", "Brussels hosts the European Union's headquarters."] },
  NLD: { fr: ["Un quart du pays se trouve sous le niveau de la mer.", "Il y a plus de vélos que d'habitants."],
         en: ["A quarter of the country lies below sea level.", "There are more bicycles than people."] },
  LUX: { fr: ["Les transports publics y sont gratuits pour tout le monde."],
         en: ["Public transport is free for everyone."] },
  CHE: { fr: ["Quatre langues officielles pour un seul petit pays.", "Le pays n'a pas fait la guerre depuis plus de deux siècles."],
         en: ["Four official languages in one small country.", "It has stayed out of war for over two centuries."] },
  AUT: { fr: ["Mozart y est né, à Salzbourg.", "Le pays est couvert aux deux tiers par les Alpes."],
         en: ["Mozart was born here, in Salzburg.", "Two-thirds of the country is covered by the Alps."] },
  MCO: { fr: ["Le deuxième plus petit pays du monde, après le Vatican."],
         en: ["The world's second-smallest country, after the Vatican."] },
  LIE: { fr: ["Un pays sans aucun aéroport, coincé entre la Suisse et l'Autriche."],
         en: ["A country with no airport at all, wedged between Switzerland and Austria."] },

  GBR: { fr: ["Quatre nations en une : Angleterre, Écosse, Pays de Galles et Irlande du Nord.", "Le métro de Londres est le plus ancien du monde.", "Aucun point du pays n'est à plus de 120 km de la mer."],
         en: ["Four nations in one: England, Scotland, Wales and Northern Ireland.", "The London Underground is the oldest metro in the world.", "No spot in the country is more than 120 km from the sea."] },
  IRL: { fr: ["Son surnom est « l'île d'émeraude », pour ses prairies toujours vertes.", "Le trèfle, et non la harpe, est son emblème le plus connu."],
         en: ["Nicknamed the Emerald Isle for its endlessly green fields.", "The shamrock, not the harp, is its best-known emblem."] },
  ISL: { fr: ["L'île est posée sur une faille où deux plaques s'écartent.", "Presque toute son électricité vient des volcans et de l'eau."],
         en: ["The island sits on a rift where two plates pull apart.", "Almost all its electricity comes from volcanoes and water."] },
  NOR: { fr: ["Ses fjords ont été creusés par les glaciers.", "Au nord, le soleil ne se couche pas de l'été."],
         en: ["Its fjords were carved out by glaciers.", "In the north the sun does not set all summer."] },
  SWE: { fr: ["Le prix Nobel y est remis chaque année.", "Le pays compte près de cent mille lacs."],
         en: ["The Nobel Prize is awarded here every year.", "The country has nearly a hundred thousand lakes."] },
  DNK: { fr: ["Le Danemark a inventé les briques Lego."],
         en: ["Denmark invented Lego bricks."] },
  FIN: { fr: ["Le pays des mille lacs — il y en a en réalité 188 000."],
         en: ["The land of a thousand lakes — there are actually 188,000."] },
  EST: { fr: ["Un des premiers pays à avoir permis de voter par internet."],
         en: ["One of the first countries where you could vote online."] },
  LVA: { fr: ["Riga possède le plus grand ensemble d'immeubles Art nouveau d'Europe."],
         en: ["Riga has Europe's largest collection of Art Nouveau buildings."] },
  LTU: { fr: ["Le pays revendique le centre géographique de l'Europe."],
         en: ["The country claims the geographical centre of Europe."] },

  ESP: { fr: ["La Sagrada Família de Barcelone est en chantier depuis plus de 140 ans.", "Le pays a plus de 8 000 km de côtes.", "La sieste y a même donné son nom au mot français."],
         en: ["Barcelona's Sagrada Família has been under construction for over 140 years.", "The country has more than 8,000 km of coastline.", "The word 'siesta' comes from here."] },
  PRT: { fr: ["Le pays produit la moitié du liège du monde.", "Ses frontières sont presque inchangées depuis le XIIIe siècle."],
         en: ["The country produces half the world's cork.", "Its borders have barely changed since the 13th century."] },
  ITA: { fr: ["Rome contient un pays entier : le Vatican.", "Le pays a plus de sites classés au patrimoine mondial que tout autre.", "Le Vésuve est le seul volcan actif d'Europe continentale."],
         en: ["Rome contains an entire country: the Vatican.", "It has more World Heritage sites than any other country.", "Vesuvius is mainland Europe's only active volcano."] },
  GRC: { fr: ["Le pays compte environ 6 000 îles, dont 227 habitées.", "Les Jeux olympiques y sont nés il y a près de 3 000 ans."],
         en: ["The country has some 6,000 islands, 227 of them inhabited.", "The Olympic Games were born here nearly 3,000 years ago."] },
  MLT: { fr: ["Un archipel minuscule au milieu de la Méditerranée."],
         en: ["A tiny archipelago in the middle of the Mediterranean."] },
  AND: { fr: ["Ce petit pays des Pyrénées a deux chefs d'État à la fois."],
         en: ["This little Pyrenean country has two heads of state at once."] },
  SMR: { fr: ["La plus vieille république du monde, perchée sur un mont."],
         en: ["The world's oldest republic, perched on a single mountain."] },
  VAT: { fr: ["Le plus petit pays du monde : on en fait le tour à pied en une heure."],
         en: ["The smallest country on Earth: you can walk around it in an hour."] },
  CYP: { fr: ["L'île est partagée en deux depuis 1974."],
         en: ["The island has been split in two since 1974."] },

  POL: { fr: ["Marie Curie, deux fois prix Nobel, était polonaise.", "La forêt de Białowieża abrite les derniers bisons d'Europe."],
         en: ["Marie Curie, twice a Nobel laureate, was Polish.", "Białowieża Forest shelters Europe's last wild bison."] },
  CZE: { fr: ["On y boit plus de bière par habitant que partout ailleurs."],
         en: ["It drinks more beer per person than anywhere else on Earth."] },
  SVK: { fr: ["Le pays compte plus de 6 000 grottes."],
         en: ["The country has more than 6,000 caves."] },
  HUN: { fr: ["Budapest est née de deux villes, Buda et Pest, réunies par un pont."],
         en: ["Budapest was born of two towns, Buda and Pest, joined by a bridge."] },
  SVN: { fr: ["Plus de la moitié du pays est couverte de forêts."],
         en: ["More than half the country is covered in forest."] },
  HRV: { fr: ["La cravate tire son nom des cavaliers croates."],
         en: ["The necktie takes its name from Croatian horsemen."] },

  ROU: { fr: ["Les Carpates y abritent la plus grande population d'ours bruns d'Europe."],
         en: ["The Carpathians hold Europe's largest brown bear population."] },
  BGR: { fr: ["Le pays produit une grande part de l'essence de rose du monde."],
         en: ["The country produces much of the world's rose oil."] },
  SRB: { fr: ["Belgrade se dresse au confluent du Danube et de la Save."],
         en: ["Belgrade stands where the Danube and the Sava meet."] },
  BIH: { fr: ["Le pont de Mostar a été reconstruit pierre par pierre après sa destruction."],
         en: ["The bridge at Mostar was rebuilt stone by stone after it was destroyed."] },
  MNE: { fr: ["Son nom signifie « montagne noire »."],
         en: ["Its name means 'black mountain'."] },
  MKD: { fr: ["Le lac d'Ohrid est l'un des plus anciens lacs du monde."],
         en: ["Lake Ohrid is one of the oldest lakes on Earth."] },
  ALB: { fr: ["Le pays est hérissé de milliers de bunkers en béton."],
         en: ["The country is dotted with thousands of concrete bunkers."] },

  RUS: { fr: ["Le plus grand pays du monde : il couvre onze fuseaux horaires.", "Le lac Baïkal contient un cinquième de l'eau douce liquide de la planète.", "Le Transsibérien met une semaine à traverser le pays."],
         en: ["The largest country on Earth, spanning eleven time zones.", "Lake Baikal holds a fifth of the planet's liquid fresh water.", "The Trans-Siberian railway takes a week to cross the country."] },
  UKR: { fr: ["Ses terres noires comptent parmi les plus fertiles du monde.", "Le métro de Kiev possède l'une des stations les plus profondes du monde."],
         en: ["Its black soil is among the most fertile on Earth.", "Kyiv's metro has one of the deepest stations in the world."] },
  BLR: { fr: ["Près de 40 % du pays est couvert de forêts."],
         en: ["Nearly 40% of the country is forest."] },
  MDA: { fr: ["Le pays abrite l'une des plus grandes caves à vin du monde."],
         en: ["The country holds one of the world's largest wine cellars."] },

  // ============================================================ ASIA

  TUR: { fr: ["Istanbul est la seule grande ville à cheval sur deux continents.", "La Cappadoce est creusée de villes souterraines entières."],
         en: ["Istanbul is the only major city straddling two continents.", "Cappadocia is hollowed out with entire underground cities."] },
  SYR: { fr: ["Damas est l'une des plus vieilles villes habitées sans interruption."],
         en: ["Damascus is one of the oldest continuously inhabited cities."] },
  LBN: { fr: ["Le cèdre du drapeau pousse encore dans les montagnes du pays."],
         en: ["The cedar on the flag still grows in the country's mountains."] },
  ISR: { fr: ["La mer Morte, à sa frontière, est le point le plus bas de la terre ferme.", "On y flotte sans effort tant l'eau est salée."],
         en: ["The Dead Sea on its border is the lowest point on dry land.", "The water is so salty you float without trying."] },
  PSE: { fr: ["Jéricho est considérée comme l'une des plus anciennes villes du monde."],
         en: ["Jericho is considered one of the oldest cities in the world."] },
  JOR: { fr: ["Pétra est taillée directement dans la falaise de grès rose."],
         en: ["Petra is carved straight into the pink sandstone cliff."] },
  IRQ: { fr: ["L'écriture est née ici, entre le Tigre et l'Euphrate."],
         en: ["Writing was born here, between the Tigris and the Euphrates."] },
  SAU: { fr: ["Le pays n'a pas un seul fleuve permanent.", "Le Rub al-Khali est le plus grand désert de sable continu du monde."],
         en: ["The country has not one permanent river.", "The Rub' al Khali is the largest continuous sand desert on Earth."] },
  YEM: { fr: ["L'île de Socotra abrite des arbres qui ne poussent nulle part ailleurs."],
         en: ["Socotra island grows trees found nowhere else on Earth."] },
  OMN: { fr: ["L'encens du pays s'exportait déjà dans l'Antiquité."],
         en: ["Its frankincense was already being exported in ancient times."] },
  ARE: { fr: ["Dubaï abrite la plus haute tour du monde, la Burj Khalifa."],
         en: ["Dubai is home to the world's tallest tower, the Burj Khalifa."] },
  QAT: { fr: ["Une péninsule de désert devenue l'un des pays les plus riches du monde."],
         en: ["A desert peninsula that became one of the world's richest countries."] },
  BHR: { fr: ["Un archipel relié à l'Arabie saoudite par une longue chaussée."],
         en: ["An archipelago linked to Saudi Arabia by a long causeway."] },
  KWT: { fr: ["Le pays est presque entièrement désertique."],
         en: ["The country is almost entirely desert."] },

  KAZ: { fr: ["Le neuvième plus grand pays du monde, et le plus grand sans accès à la mer."],
         en: ["The ninth-largest country on Earth, and the largest with no coast."] },
  UZB: { fr: ["Samarcande était une étape majeure de la route de la Soie."],
         en: ["Samarkand was a major stop on the Silk Road."] },
  TKM: { fr: ["Un cratère de gaz y brûle sans interruption depuis des décennies."],
         en: ["A gas crater here has been burning non-stop for decades."] },
  TJK: { fr: ["Plus de 90 % du pays est montagneux."],
         en: ["Over 90% of the country is mountainous."] },
  KGZ: { fr: ["Le lac Issyk-Koul ne gèle jamais, malgré l'altitude."],
         en: ["Lake Issyk-Kul never freezes, despite the altitude."] },
  AFG: { fr: ["Le lapis-lazuli du pays ornait déjà les tombes des pharaons."],
         en: ["Its lapis lazuli already adorned the tombs of the pharaohs."] },
  AZE: { fr: ["Son nom signifie « la terre du feu », pour ses feux naturels de gaz."],
         en: ["Its name means 'land of fire', after its natural gas flames."] },
  ARM: { fr: ["Le mont Ararat, son symbole, se trouve juste de l'autre côté de la frontière."],
         en: ["Mount Ararat, its symbol, stands just across the border."] },
  GEO: { fr: ["On y fait du vin depuis 8 000 ans, dans des jarres enterrées."],
         en: ["Wine has been made here for 8,000 years, in buried clay jars."] },
  IRN: { fr: ["Les qanats, canaux souterrains, y irriguent le désert depuis 3 000 ans.", "Le pays s'appelait Perse jusqu'en 1935."],
         en: ["Qanats, underground channels, have watered its deserts for 3,000 years.", "The country was called Persia until 1935."] },

  IND: { fr: ["Le pays le plus peuplé du monde.", "On y parle plus de 20 langues officielles.", "Les chiffres que nous écrivons viennent d'Inde."],
         en: ["The most populous country in the world.", "It has more than 20 official languages.", "The digits we write come from India."] },
  PAK: { fr: ["Le K2, deuxième sommet du monde, se dresse à sa frontière.", "La vallée de l'Indus abritait une civilisation il y a 4 500 ans."],
         en: ["K2, the world's second-highest peak, rises on its border.", "The Indus valley held a civilisation 4,500 years ago."] },
  BGD: { fr: ["Le pays est sillonné par plus de 700 rivières."],
         en: ["The country is threaded with more than 700 rivers."] },
  NPL: { fr: ["L'Everest, toit du monde, se dresse à sa frontière.", "Son drapeau est le seul au monde qui ne soit pas rectangulaire."],
         en: ["Everest, the roof of the world, stands on its border.", "Its flag is the only non-rectangular national flag."] },
  BTN: { fr: ["Le pays mesure son « bonheur national brut » plutôt que sa richesse."],
         en: ["The country measures Gross National Happiness rather than wealth."] },
  LKA: { fr: ["L'île est surnommée « la larme de l'Inde » pour sa forme."],
         en: ["The island is nicknamed 'the teardrop of India' for its shape."] },
  MDV: { fr: ["Le pays le plus plat du monde : deux mètres au-dessus des flots."],
         en: ["The flattest country on Earth: two metres above the waves."] },

  CHN: { fr: ["La Grande Muraille court sur plus de 20 000 kilomètres.", "Tout le pays vit à la même heure, malgré son immensité.", "Le papier, la boussole et la poudre y ont été inventés."],
         en: ["The Great Wall runs for more than 20,000 kilometres.", "The whole country keeps one single time zone, vast as it is.", "Paper, the compass and gunpowder were invented here."] },
  MNG: { fr: ["Le pays le moins densément peuplé du monde.", "Beaucoup d'habitants vivent encore sous la yourte."],
         en: ["The least densely populated country on Earth.", "Many people still live in round felt tents."] },
  JPN: { fr: ["L'archipel compte près de 14 000 îles.", "Le pays connaît plus de 1 500 séismes par an.", "Le Shinkansen roule depuis 1964 sans un seul accident mortel."],
         en: ["The archipelago counts nearly 14,000 islands.", "The country feels over 1,500 earthquakes a year.", "The Shinkansen has run since 1964 without a single fatal crash."] },
  KOR: { fr: ["L'alphabet coréen a été inventé de toutes pièces au XVe siècle.", "Le pays est l'un des plus connectés du monde."],
         en: ["The Korean alphabet was invented from scratch in the 15th century.", "It is one of the most connected countries in the world."] },
  PRK: { fr: ["Le pays le plus fermé du monde."],
         en: ["The most closed-off country in the world."] },

  THA: { fr: ["Le seul pays d'Asie du Sud-Est jamais colonisé.", "Son nom signifie « pays des hommes libres »."],
         en: ["The only Southeast Asian country never colonised.", "Its name means 'land of the free'."] },
  VNM: { fr: ["La baie d'Along est hérissée de près de 2 000 pitons calcaires.", "Le pays est le deuxième exportateur de café du monde."],
         en: ["Ha Long Bay bristles with nearly 2,000 limestone pillars.", "The country is the world's second-largest coffee exporter."] },
  LAO: { fr: ["Le seul pays d'Asie du Sud-Est sans accès à la mer."],
         en: ["The only Southeast Asian country with no coastline."] },
  KHM: { fr: ["Angkor Vat est le plus grand monument religieux du monde."],
         en: ["Angkor Wat is the largest religious monument in the world."] },
  MMR: { fr: ["La plaine de Bagan compte plus de 2 000 temples."],
         en: ["The plain of Bagan holds more than 2,000 temples."] },
  MYS: { fr: ["Ses forêts comptent parmi les plus anciennes du monde."],
         en: ["Its rainforests are among the oldest on Earth."] },
  SGP: { fr: ["Une cité-État qui agrandit son territoire en gagnant sur la mer."],
         en: ["A city-state that grows its land by reclaiming it from the sea."] },
  IDN: { fr: ["Plus de 17 000 îles composent le pays.", "Le dragon de Komodo n'y vit que sur quelques îles."],
         en: ["More than 17,000 islands make up the country.", "The Komodo dragon lives on just a handful of its islands."] },
  PHL: { fr: ["L'archipel compte plus de 7 000 îles."],
         en: ["The archipelago counts more than 7,000 islands."] },
  BRN: { fr: ["Un petit sultanat entouré par la Malaisie et la forêt."],
         en: ["A small sultanate ringed by Malaysia and rainforest."] },
  TLS: { fr: ["L'un des plus jeunes pays du monde, indépendant depuis 2002."],
         en: ["One of the world's youngest countries, independent since 2002."] },

  // ==================================================== NORTH AMERICA

  CAN: { fr: ["Le pays possède plus de lacs que tout le reste du monde réuni.", "Sa frontière avec les États-Unis est la plus longue du monde.", "Deux langues officielles : l'anglais et le français."],
         en: ["The country has more lakes than the rest of the world combined.", "Its border with the United States is the longest on Earth.", "Two official languages: English and French."] },
  USA: { fr: ["Le pays compte 50 États et six fuseaux horaires.", "Le Grand Canyon est profond de plus d'un kilomètre.", "Le parc de Yellowstone est le plus ancien parc national du monde."],
         en: ["The country has 50 states and six time zones.", "The Grand Canyon is over a kilometre deep.", "Yellowstone was the world's first national park."] },
  MEX: { fr: ["Le chocolat, la tomate et le maïs viennent d'ici.", "Mexico est bâtie sur un ancien lac et s'enfonce chaque année."],
         en: ["Chocolate, tomatoes and maize all come from here.", "Mexico City is built on a former lake and sinks a little each year."] },

  GTM: { fr: ["Le pays compte 37 volcans, dont plusieurs en activité."],
         en: ["The country has 37 volcanoes, several of them active."] },
  BLZ: { fr: ["Sa barrière de corail est la deuxième plus grande du monde."],
         en: ["Its barrier reef is the second-largest in the world."] },
  SLV: { fr: ["Le plus petit pays d'Amérique continentale."],
         en: ["The smallest country on the American mainland."] },
  HND: { fr: ["Copán abrite certaines des plus fines sculptures mayas."],
         en: ["Copán holds some of the finest Maya carvings."] },
  NIC: { fr: ["Le lac Nicaragua abrite des requins d'eau douce."],
         en: ["Lake Nicaragua is home to freshwater sharks."] },
  CRI: { fr: ["Le pays a supprimé son armée en 1949.", "Il abrite 5 % des espèces vivantes de la planète."],
         en: ["The country abolished its army in 1949.", "It shelters 5% of all the species on the planet."] },
  PAN: { fr: ["Son canal relie deux océans en une journée de navigation."],
         en: ["Its canal links two oceans in a single day's sailing."] },

  CUB: { fr: ["La plus grande île des Caraïbes.", "Les voitures américaines des années 50 y roulent encore."],
         en: ["The largest island in the Caribbean.", "American cars from the 1950s still drive its streets."] },
  HTI: { fr: ["La première république noire indépendante du monde."],
         en: ["The world's first independent Black republic."] },
  DOM: { fr: ["Le pays partage son île avec Haïti."],
         en: ["The country shares its island with Haiti."] },
  JAM: { fr: ["Le reggae est né dans ses quartiers de Kingston."],
         en: ["Reggae was born in the neighbourhoods of Kingston."] },
  BHS: { fr: ["Un archipel de plus de 700 îles aux eaux turquoise."],
         en: ["An archipelago of more than 700 islands in turquoise water."] },
  TTO: { fr: ["Le steelpan, fait de bidons de pétrole, y a été inventé."],
         en: ["The steelpan, made from oil drums, was invented here."] },
  BRB: { fr: ["L'île est presque entièrement faite de corail."],
         en: ["The island is made almost entirely of coral."] },
  LCA: { fr: ["Ses deux pitons volcaniques sortent droit de la mer."],
         en: ["Its two volcanic peaks rise straight out of the sea."] },
  GRD: { fr: ["Surnommée « l'île aux épices » pour sa noix de muscade."],
         en: ["Nicknamed the Spice Isle for its nutmeg."] },
  VCT: { fr: ["Un chapelet d'îlots aux plages de sable noir volcanique."],
         en: ["A string of islets with black volcanic sand."] },
  ATG: { fr: ["On dit qu'il y a une plage pour chaque jour de l'année."],
         en: ["They say there is a beach for every day of the year."] },
  DMA: { fr: ["L'île abrite un lac bouillonnant chauffé par le volcan."],
         en: ["The island has a boiling lake heated by the volcano beneath."] },
  KNA: { fr: ["Le plus petit pays des Amériques."],
         en: ["The smallest country in the Americas."] },

  // ==================================================== SOUTH AMERICA

  COL: { fr: ["Le pays est le premier producteur d'émeraudes du monde.", "Il touche à la fois l'Atlantique et le Pacifique."],
         en: ["The country is the world's leading emerald producer.", "It touches both the Atlantic and the Pacific."] },
  VEN: { fr: ["La chute du Salto Ángel est la plus haute du monde."],
         en: ["Angel Falls is the tallest waterfall in the world."] },
  ECU: { fr: ["Les Galápagos, à 1 000 km au large, appartiennent au pays."],
         en: ["The Galápagos, 1,000 km offshore, belong to the country."] },
  PER: { fr: ["Le Machu Picchu est resté caché dans la montagne pendant des siècles.", "La pomme de terre vient des Andes péruviennes."],
         en: ["Machu Picchu stayed hidden in the mountains for centuries.", "The potato comes from the Peruvian Andes."] },
  BOL: { fr: ["Le salar d'Uyuni devient le plus grand miroir du monde à la saison des pluies."],
         en: ["The Uyuni salt flat becomes the world's largest mirror in the rainy season."] },
  GUY: { fr: ["Le seul pays d'Amérique du Sud dont la langue officielle est l'anglais."],
         en: ["The only South American country whose official language is English."] },
  SUR: { fr: ["Le pays le plus boisé du monde en proportion."],
         en: ["Proportionally the most forested country on Earth."] },

  BRA: { fr: ["Le pays abrite 60 % de la forêt amazonienne.", "Il touche tous les pays d'Amérique du Sud sauf deux.", "C'est le seul pays lusophone du continent."],
         en: ["The country holds 60% of the Amazon rainforest.", "It borders every South American country but two.", "It is the continent's only Portuguese-speaking country."] },
  ARG: { fr: ["Le pays s'étire sur près de 3 700 km du nord au sud.", "L'Aconcagua est le plus haut sommet hors d'Asie."],
         en: ["The country stretches nearly 3,700 km from north to south.", "Aconcagua is the highest peak outside Asia."] },
  CHL: { fr: ["Un ruban de terre long de 4 300 km et large de 180 en moyenne.", "Le désert d'Atacama est l'endroit le plus sec du monde."],
         en: ["A ribbon of land 4,300 km long and 180 km wide on average.", "The Atacama is the driest place on Earth."] },
  PRY: { fr: ["Le pays a deux langues officielles, dont le guarani."],
         en: ["The country has two official languages, one of them Guaraní."] },
  URY: { fr: ["Il y a environ trois vaches pour chaque habitant."],
         en: ["There are roughly three cows for every person."] },

  // ========================================================== OCEANIA

  AUS: { fr: ["La Grande Barrière de corail se voit depuis l'espace.", "Le pays est aussi un continent à lui tout seul.", "Les kangourous y sont plus nombreux que les habitants."],
         en: ["The Great Barrier Reef is visible from space.", "The country is also a continent all by itself.", "Kangaroos outnumber people."] },
  NZL: { fr: ["Le pays compte environ cinq moutons pour un habitant.", "Le kiwi, oiseau qui ne vole pas, n'existe qu'ici."],
         en: ["There are roughly five sheep for every person.", "The kiwi, a bird that cannot fly, lives only here."] },
  PNG: { fr: ["On y parle plus de 800 langues, plus que dans tout autre pays."],
         en: ["More than 800 languages are spoken here, more than anywhere else."] },
  FJI: { fr: ["Un archipel de plus de 300 îles, dont un tiers habitées."],
         en: ["An archipelago of over 300 islands, a third of them inhabited."] },
  SLB: { fr: ["Certains habitants y naissent avec les cheveux blonds."],
         en: ["Some islanders are born with naturally blond hair."] },
  VUT: { fr: ["On peut y approcher un lac de lave en fusion."],
         en: ["You can walk up to a lake of molten lava here."] },
  WSM: { fr: ["L'un des premiers pays à voir le lever du soleil chaque jour."],
         en: ["One of the first countries to see the sunrise each day."] },
  TON: { fr: ["Le seul pays du Pacifique à n'avoir jamais été colonisé."],
         en: ["The only Pacific nation never to have been colonised."] },
  KIR: { fr: ["Le pays est à cheval sur l'équateur et sur la ligne de changement de date."],
         en: ["The country straddles both the equator and the date line."] },
  FSM: { fr: ["Les ruines de Nan Madol sont bâties sur des îlots artificiels."],
         en: ["The ruins of Nan Madol are built on artificial islets."] },
  MHL: { fr: ["Ses atolls encerclent des lagons plus grands que les îles elles-mêmes."],
         en: ["Its atolls ring lagoons larger than the islands themselves."] },
  NRU: { fr: ["Le plus petit pays insulaire du monde : on en fait le tour en vingt minutes."],
         en: ["The world's smallest island country: you can drive around it in twenty minutes."] },
  PLW: { fr: ["On y nage au milieu de méduses qui ne piquent pas."],
         en: ["You can swim among jellyfish that do not sting."] },
  TUV: { fr: ["Le pays tire une part de ses revenus de son domaine internet, le .tv."],
         en: ["The country earns part of its income from its internet domain, .tv."] },
};
