// Anecdotes for the 54 African countries, lifted verbatim from
// africa-capitals-game so the two games tell the same stories.
// Regenerate with: node extract-africa-facts.mjs <path to that index.html>
export const AFRICA_FACTS = {
  AGO: { fr: ["Le portugais y est la langue officielle.","Les chutes de Kalandula comptent parmi les plus grandes d'Afrique.","L'hippotrague noir géant, très rare, ne vit qu'en Angola."],
        en: ["Portuguese is the official language.","Kalandula Falls is among Africa's largest waterfalls.","The rare giant sable antelope lives only in Angola."] },
  BDI: { fr: ["Une des sources les plus lointaines du Nil.","Gitega est devenue la capitale en 2019, à la place de Bujumbura.","Le lac Tanganyika, à sa frontière, est le 2e plus profond du monde."],
        en: ["One of the Nile's most distant sources.","Gitega became the capital in 2019, replacing Bujumbura.","Lake Tanganyika on its border is the world's 2nd-deepest lake."] },
  BEN: { fr: ["Berceau historique du vaudou.","Le village de Ganvié est bâti sur pilotis au milieu d'un lac.","Porto-Novo est la capitale, mais Cotonou est la plus grande ville."],
        en: ["The historical birthplace of voodoo.","Ganvié village is built on stilts in the middle of a lake.","Porto-Novo is the capital, but Cotonou is the biggest city."] },
  BFA: { fr: ["Son nom signifie « pays des hommes intègres ».","Ouagadougou accueille le FESPACO, le plus grand festival de cinéma d'Afrique.","Ses habitants s'appellent les Burkinabè."],
        en: ["Its name means 'land of honest people'.","Ouagadougou hosts FESPACO, Africa's biggest film festival.","Its people are called the Burkinabè."] },
  BWA: { fr: ["Le delta de l’Okavango est un paradis animalier.","Abrite la plus grande population d'éléphants du monde.","Le désert du Kalahari couvre la majeure partie du pays."],
        en: ["The Okavango Delta is a wildlife paradise.","Home to the world's largest elephant population.","The Kalahari Desert covers most of the country."] },
  CAF: { fr: ["Pays enclavé au cœur du continent.","Gorilles et éléphants de forêt vivent dans la réserve de Dzanga-Sangha.","La rivière Oubangui coule le long de Bangui."],
        en: ["A landlocked country at the continent's heart.","Gorillas and forest elephants live in the Dzanga-Sangha reserve.","The Ubangi River flows past Bangui."] },
  CIV: { fr: ["Premier producteur mondial de cacao.","La basilique de Yamoussoukro est l'une des plus grandes églises du monde.","Abidjan est la plus grande ville, mais Yamoussoukro est la capitale."],
        en: ["The world's top cocoa producer.","Yamoussoukro's basilica is one of the largest churches on Earth.","Abidjan is the biggest city, but Yamoussoukro is the capital."] },
  CMR: { fr: ["Surnommé « l'Afrique en miniature ».","Le mont Cameroun est un volcan actif au bord de l'océan.","Son équipe de football, les Lions Indomptables, est légendaire."],
        en: ["Nicknamed 'Africa in miniature'.","Mount Cameroon is an active volcano right by the ocean.","Its football team, the Indomitable Lions, is legendary."] },
  COD: { fr: ["2e plus grand pays d'Afrique, riche en forêts.","Le fleuve Congo est le plus profond du monde.","L'okapi, cousin de la girafe, ne vit qu'en RDC."],
        en: ["Africa's 2nd-largest country, rich in rainforest.","The Congo River is the deepest on Earth.","The okapi, a giraffe cousin, lives only in DR Congo."] },
  COG: { fr: ["Traversé par l’équateur.","Brazzaville et Kinshasa sont les deux capitales les plus proches du monde.","Des gorilles des plaines vivent dans ses forêts."],
        en: ["The equator runs through it.","Brazzaville and Kinshasa are the world's two closest capitals.","Lowland gorillas live in its forests."] },
  COM: { fr: ["Surnommées les « îles de la Lune ».","Premier producteur mondial d'ylang-ylang, une fleur à parfum.","Le volcan Karthala est l'un des plus actifs du monde."],
        en: ["Nicknamed the 'islands of the Moon'.","The world's top grower of ylang-ylang, a perfume flower.","Karthala volcano is one of the most active on Earth."] },
  CPV: { fr: ["Un archipel de 10 îles volcaniques dans l’Atlantique.","Les îles étaient désertes avant l'arrivée des navigateurs au 15e siècle.","La morna, sa musique traditionnelle, est classée à l'UNESCO."],
        en: ["An archipelago of 10 volcanic islands in the Atlantic.","The islands were uninhabited until sailors arrived in the 1400s.","Its traditional morna music is UNESCO-listed."] },
  DJI: { fr: ["Le lac Assal est le point le plus bas d'Afrique.","Le lac Assal est bien plus salé que la mer.","Le pays garde l'entrée de la mer Rouge."],
        en: ["Lake Assal is the lowest point in Africa.","Lake Assal is far saltier than the sea.","The country guards the entrance to the Red Sea."] },
  DZA: { fr: ["Le plus grand pays d'Afrique par sa superficie.","Le Sahara couvre environ 80 % de l'Algérie.","Alger est surnommée « Alger la Blanche » pour ses immeubles blancs."],
        en: ["The largest country in Africa by area.","The Sahara covers about 80% of Algeria.","Algiers is nicknamed 'Algiers the White' for its white buildings."] },
  EGY: { fr: ["Les pyramides de Gizeh ont plus de 4 500 ans.","Le Nil, qui traverse l'Égypte, est l'un des plus longs fleuves du monde.","L'agglomération du Caire compte plus de 20 millions d'habitants."],
        en: ["The Giza pyramids are over 4,500 years old.","The Nile, flowing through Egypt, is one of the world's longest rivers.","Greater Cairo is home to more than 20 million people."] },
  ERI: { fr: ["Asmara est célèbre pour son architecture Art déco.","Asmara est classée au patrimoine mondial de l'UNESCO.","Son nom vient du mot grec désignant la mer Rouge."],
        en: ["Asmara is famous for its Art Deco architecture.","Asmara is a UNESCO World Heritage city.","Its name comes from the Greek word for the Red Sea."] },
  ETH: { fr: ["Jamais colonisée, elle a son propre calendrier.","Lucy, célèbre fossile d'un ancêtre humain, y fut découverte.","Le café aurait été découvert en Éthiopie."],
        en: ["Never colonized, it has its own calendar.","Lucy, the famous early-human fossil, was found here.","Coffee is said to have been discovered in Ethiopia."] },
  GAB: { fr: ["Près de 90 % du territoire est forêt.","Au parc de Loango, hippopotames et éléphants se baladent sur la plage.","L'équateur traverse le pays."],
        en: ["Almost 90% is covered by forest.","In Loango park, hippos and elephants stroll on the beach.","The equator crosses the country."] },
  GHA: { fr: ["1er pays d’Afrique subsaharienne indépendant (1957).","Le lac Volta est l'un des plus grands lacs artificiels du monde.","Le Ghana s'appelait autrefois la « Côte de l'Or »."],
        en: ["First independent sub-Saharan country (1957).","Lake Volta is one of the world's largest man-made lakes.","Ghana was once known as the 'Gold Coast'."] },
  GIN: { fr: ["Le fleuve Niger y prend sa source.","Surnommée « le château d'eau de l'Afrique de l'Ouest ».","Son sous-sol regorge de bauxite, le minerai de l'aluminium."],
        en: ["The Niger River begins here.","Nicknamed 'the water tower of West Africa'.","Its ground is rich in bauxite, the ore used to make aluminium."] },
  GMB: { fr: ["Le plus petit pays d'Afrique continentale.","Le pays suit le fleuve Gambie sur toute sa longueur.","Il est presque entièrement entouré par le Sénégal."],
        en: ["The smallest country in mainland Africa.","The country hugs the Gambia River along its whole length.","It is almost completely surrounded by Senegal."] },
  GNB: { fr: ["Connu pour ses îles Bijagos.","Des hippopotames d'eau salée vivent dans l'archipel des Bijagos.","La noix de cajou est sa grande spécialité."],
        en: ["Known for the Bijagós islands.","Saltwater hippos live in the Bijagós archipelago.","Cashew nuts are its big specialty."] },
  GNQ: { fr: ["Seul pays africain hispanophone.","Sa capitale, Malabo, est sur une île, pas sur le continent.","Une nouvelle capitale se construit en pleine forêt."],
        en: ["The only Spanish-speaking African country.","Its capital, Malabo, sits on an island, not the mainland.","A brand-new capital is being built in the rainforest."] },
  KEN: { fr: ["La grande migration du Masai Mara y est célèbre.","Le pays doit son nom au mont Kenya, 2e sommet d'Afrique.","Ses coureurs de fond sont parmi les meilleurs du monde."],
        en: ["The Masai Mara's great migration is famous here.","It is named after Mount Kenya, Africa's 2nd-highest peak.","Its long-distance runners are among the world's best."] },
  LBR: { fr: ["Fondé au 19e siècle par des Afro-Américains affranchis.","C'est la plus ancienne république d'Afrique (1847).","Son drapeau ressemble beaucoup à celui des États-Unis."],
        en: ["Founded in the 1800s by freed African-Americans.","It is Africa's oldest republic (1847).","Its flag looks a lot like the US flag."] },
  LBY: { fr: ["Plus de 90 % du pays est couvert par le Sahara.","La Libye possède les plus grandes réserves de pétrole d'Afrique.","Leptis Magna compte parmi les plus belles ruines romaines du monde."],
        en: ["Over 90% of the country is Sahara desert.","Libya has Africa's largest oil reserves.","Leptis Magna is among the world's finest Roman ruins."] },
  LSO: { fr: ["Entièrement situé à plus de 1 000 m d’altitude.","Surnommé « le royaume dans le ciel ».","Il est entièrement entouré par l'Afrique du Sud."],
        en: ["Entirely above 1,000 m elevation.","Nicknamed 'the Kingdom in the Sky'.","It is completely surrounded by South Africa."] },
  MAR: { fr: ["Fès abrite la plus vieille université du monde encore en activité.","Seuls 14 km de mer séparent le Maroc de l'Europe.","Marrakech est surnommée « la ville rouge »."],
        en: ["Fez has the world's oldest still-running university.","Only 14 km of sea separate Morocco from Europe.","Marrakesh is nicknamed 'the Red City'."] },
  MDG: { fr: ["90 % de sa faune ne vit nulle part ailleurs.","C'est la 4e plus grande île du monde.","Des baobabs géants bordent la célèbre allée des Baobabs."],
        en: ["90% of its wildlife lives nowhere else.","It is the world's 4th-largest island.","Giant baobabs line the famous Avenue of the Baobabs."] },
  MLI: { fr: ["Tombouctou fut un grand centre de savoir médiéval.","La grande mosquée de Djenné est le plus grand bâtiment en terre crue du monde.","Le fleuve Niger y forme un immense delta intérieur."],
        en: ["Timbuktu was a great medieval center of learning.","The Great Mosque of Djenné is the world's largest mud-brick building.","The Niger River forms a huge inland delta here."] },
  MOZ: { fr: ["Son drapeau arbore un fusil AK-47.","Son littoral s'étire sur environ 2 500 km.","L'île de Mozambique a donné son nom au pays."],
        en: ["Its flag features an AK-47 rifle.","Its coastline stretches about 2,500 km.","The Island of Mozambique gave the country its name."] },
  MRT: { fr: ["Un de ses trains de minerai est parmi les plus longs du monde.","La structure de Richat, « l'œil de l'Afrique », se voit depuis l'espace.","Le désert couvre environ 90 % du pays."],
        en: ["Home to one of the world's longest trains.","The Richat Structure, the 'Eye of Africa', is visible from space.","Desert covers about 90% of the country."] },
  MUS: { fr: ["Le dodo, oiseau disparu, vivait sur cette île.","L'île est née d'éruptions volcaniques.","Un timbre mauricien de 1847 est l'un des plus rares du monde."],
        en: ["The extinct dodo bird lived on this island.","The island was born from volcanic eruptions.","An 1847 Mauritius stamp is one of the rarest in the world."] },
  MWI: { fr: ["Le lac Malawi abrite des centaines d’espèces de poissons.","Le lac Malawi couvre environ un quart du pays.","Surnommé « le cœur chaud de l'Afrique »."],
        en: ["Lake Malawi holds hundreds of fish species.","Lake Malawi covers about a quarter of the country.","Nicknamed 'the warm heart of Africa'."] },
  NAM: { fr: ["Les dunes du Namib comptent parmi les plus hautes.","Le Namib serait le plus vieux désert du monde.","C'est l'un des pays les moins densément peuplés du monde."],
        en: ["The Namib's dunes are among Earth's tallest.","The Namib may be the world's oldest desert.","One of the least densely populated countries on Earth."] },
  NER: { fr: ["Plus des deux tiers du pays sont dans le Sahara.","Le pays doit son nom au fleuve Niger.","L'arbre du Ténéré fut longtemps l'arbre le plus isolé du monde."],
        en: ["More than two-thirds lies in the Sahara.","The country is named after the Niger River.","The Tree of Ténéré was once the loneliest tree on Earth."] },
  NGA: { fr: ["Pays le plus peuplé d'Afrique.","Nollywood, son industrie du cinéma, tourne des centaines de films par an.","Plus de 500 langues y sont parlées."],
        en: ["The most populous country in Africa.","Its film industry, Nollywood, shoots hundreds of movies a year.","More than 500 languages are spoken here."] },
  RWA: { fr: ["Surnommé le « pays aux mille collines ».","Des gorilles des montagnes vivent dans le parc des Volcans.","Les sacs en plastique y sont interdits depuis 2008."],
        en: ["Nicknamed the 'land of a thousand hills'.","Mountain gorillas live in Volcanoes National Park.","Plastic bags have been banned there since 2008."] },
  SDN: { fr: ["Le Soudan compte plus de pyramides que l'Égypte !","Le Nil Bleu et le Nil Blanc se rejoignent à Khartoum.","C'était le plus grand pays d'Afrique avant 2011."],
        en: ["Sudan has more pyramids than Egypt!","The Blue Nile and White Nile meet in Khartoum.","It was Africa's largest country until 2011."] },
  SEN: { fr: ["Le lac Rose doit sa couleur à des micro-algues.","Dakar est la grande ville la plus à l'ouest de l'Afrique continentale.","L'île de Gorée, face à Dakar, est classée à l'UNESCO."],
        en: ["Lake Retba is pink thanks to micro-algae.","Dakar is mainland Africa's westernmost big city.","Gorée Island, facing Dakar, is a UNESCO site."] },
  SLE: { fr: ["Possède un des plus grands ports naturels du monde.","Son nom signifie « montagne du lion » en portugais.","Le pays est réputé pour ses diamants."],
        en: ["Has one of the world's largest natural harbors.","Its name means 'lion mountain' in Portuguese.","The country is famous for its diamonds."] },
  SOM: { fr: ["Le plus long littoral d'Afrique continentale.","L'encens et la myrrhe y sont récoltés depuis l'Antiquité.","Le chameau occupe une place essentielle dans sa culture."],
        en: ["The longest coastline of mainland Africa.","Frankincense and myrrh have been harvested here since ancient times.","Camels hold a special place in its culture."] },
  SSD: { fr: ["Le plus jeune pays du monde (2011).","Le Sudd est l'une des plus vastes zones humides du monde.","Il abrite une des plus grandes migrations d'antilopes du monde."],
        en: ["The world's youngest country (2011).","The Sudd is one of the world's largest wetlands.","Home to one of the biggest antelope migrations on Earth."] },
  STP: { fr: ["Deux îles posées sur l’équateur.","C'est le deuxième plus petit pays d'Afrique.","Le pic Cão Grande est une incroyable aiguille volcanique."],
        en: ["Two islands sitting on the equator.","It is Africa's second-smallest country.","Pico Cão Grande is an amazing volcanic spire."] },
  SWZ: { fr: ["Une des dernières monarchies absolues au monde.","Le pays a changé de nom en 2018 (ex-Swaziland).","C'est l'un des plus petits pays d'Afrique."],
        en: ["One of the world's last absolute monarchies.","The country changed its name in 2018 (formerly Swaziland).","It is one of Africa's smallest countries."] },
  SYC: { fr: ["115 îles dans l’océan Indien.","C'est le plus petit pays d'Afrique.","Le coco de mer y produit la plus grosse graine du monde."],
        en: ["115 islands in the Indian Ocean.","It is Africa's smallest country.","The coco de mer palm grows the world's largest seed."] },
  TCD: { fr: ["Le lac Tchad a beaucoup rétréci en 50 ans.","Les lacs d'Ounianga, en plein Sahara, sont classés à l'UNESCO.","Le massif de l'Ennedi cache des arches de grès spectaculaires."],
        en: ["Lake Chad has shrunk dramatically in 50 years.","The Ounianga lakes, deep in the Sahara, are UNESCO-listed.","The Ennedi massif hides spectacular sandstone arches."] },
  TGO: { fr: ["Une étroite bande de terre, de la côte au nord.","Le pays mesure moins de 60 km de large par endroits.","Les maisons-tours en terre du Koutammakou sont classées à l'UNESCO."],
        en: ["A narrow strip of land from coast to interior.","The country is less than 60 km wide in places.","The mud tower-houses of Koutammakou are UNESCO-listed."] },
  TUN: { fr: ["Des scènes de Star Wars y furent tournées dans le désert.","L'antique cité de Carthage se trouvait tout près de Tunis.","La Tunisie est le pays le plus au nord de l'Afrique."],
        en: ["Star Wars desert scenes were filmed here.","The ancient city of Carthage stood right next to Tunis.","Tunisia is Africa's northernmost country."] },
  TZA: { fr: ["Le Kilimandjaro, plus haut sommet d’Afrique, y est.","Le cratère du Ngorongoro regorge d'animaux sauvages.","Zanzibar, l'île aux épices, fait partie de la Tanzanie."],
        en: ["Mt Kilimanjaro, Africa's highest peak, is here.","The Ngorongoro Crater teems with wildlife.","Zanzibar, the spice island, is part of Tanzania."] },
  UGA: { fr: ["Partage le lac Victoria, le plus grand d’Afrique.","La moitié des gorilles des montagnes du monde y vit.","Le Nil Blanc jaillit du lac Victoria à Jinja."],
        en: ["Shares Lake Victoria, Africa's largest lake.","Half of the world's mountain gorillas live here.","The White Nile bursts out of Lake Victoria at Jinja."] },
  ZAF: { fr: ["Possède trois capitales officielles.","Nelson Mandela devint son premier président élu par tous.","Des manchots se dandinent sur les plages du Cap."],
        en: ["Has three official capital cities.","Nelson Mandela became its first president elected by all.","Penguins waddle on Cape Town's beaches."] },
  ZMB: { fr: ["Partage les chutes Victoria avec le Zimbabwe.","Les locaux appellent les chutes Victoria « la fumée qui gronde ».","Le fleuve Zambèze a donné son nom au pays."],
        en: ["Shares Victoria Falls with Zimbabwe.","Locals call Victoria Falls 'the smoke that thunders'.","The Zambezi River gave the country its name."] },
  ZWE: { fr: ["Les ruines du Grand Zimbabwe ont nommé le pays.","Le lac Kariba est l'un des plus grands lacs artificiels du monde.","Un oiseau sculpté, l'oiseau de Zimbabwe, orne son drapeau."],
        en: ["The Great Zimbabwe ruins named the country.","Lake Kariba is one of the world's largest man-made lakes.","A carved bird, the Zimbabwe Bird, adorns its flag."] },
};
